openapi: 3.0.0
info:
  title: API Documentación para Terrasol
  version: 2.0.0
servers:
<<<<<<< HEAD
  - url: http://localhost/Eva3-w-Linces/backend/api/v2
=======
  - url: http://localhost/Eva2-w-Linces/backend/api/v2
>>>>>>> origin/Caro

paths:
  /categoria_servicio/get.php:
    get:
      tags:
        - "categoria_servicio"
      summary: Obtiene todas las categorías de servicio.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de categorías de servicio.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoriaServicio'
<<<<<<< HEAD
        '404':
          description: No se encontraron categorías.
        '500':
          description: Error interno del servidor.
=======
>>>>>>> origin/Caro

  /categoria_servicio/post.php:
    post:
      tags:
        - "categoria_servicio"
      summary: Crea una nueva categoría de servicio.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoriaServicio'
      responses:
        '201':
          description: Categoría de servicio creada.
<<<<<<< HEAD
        '400':
          description: Solicitud incorrecta.
        '500':
          description: Error interno del servidor.
=======
>>>>>>> origin/Caro

  /categoria_servicio/delete.php:
    delete:
      tags:
        - "categoria_servicio"
      summary: Elimina una categoría de servicio.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Categoría de servicio eliminada.
<<<<<<< HEAD
        '404':
          description: Categoría no encontrada.
        '500':
          description: Error interno del servidor.
=======
>>>>>>> origin/Caro

  /info_contacto/get.php:
    get:
      tags:
        - "info_contacto"
      summary: Obtiene la información de contacto.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Información de contacto.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoContacto'
<<<<<<< HEAD
        '404':
          description: Información de contacto no encontrada.
        '500':
          description: Error interno del servidor.
=======
>>>>>>> origin/Caro

  /info_contacto/post.php:
    post:
      tags:
        - "info_contacto"
      summary: Crea nueva información de contacto.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InfoContacto'
      responses:
        '201':
          description: Información de contacto creada.
<<<<<<< HEAD
        '400':
          description: Solicitud incorrecta.
        '500':
          description: Error interno del servidor.
=======
>>>>>>> origin/Caro

  /info_contacto/delete.php:
    delete:
      tags:
        - "info_contacto"
<<<<<<< HEAD
      summary: Elimina una información de contacto.
      security:
        - bearerAuth: []
      requestBody:
        required: true
=======
      summary: Elimina una categoría de servicio.
      security:
        - bearerAuth: []
      requestBody:
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        '200':
<<<<<<< HEAD
          description: Información de contacto eliminada.
        '404':
          description: Información de contacto no encontrada.
        '500':
          description: Error interno del servidor.
=======
          description: Información de contacto actualizada.
>>>>>>> origin/Caro

  /historia/get.php:
    get:
      tags:
<<<<<<< HEAD
        - "historia"
=======
        - "Historia"
>>>>>>> origin/Caro
      summary: Obtiene todas las historias con imágenes.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de historias.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Historia'
<<<<<<< HEAD
        '404':
          description: No se encontraron historias.
        '500':
          description: Error interno del servidor.

  /historia/post.php:
    post:
      tags:
        - "historia"
      summary: Crea una nueva historia.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Historia'
      responses:
        '201':
          description: Historia creada.
        '400':
          description: Solicitud incorrecta.
        '500':
          description: Error interno del servidor.

  /historia/delete.php:
    delete:
      tags:
        - "historia"
      summary: Elimina una historia.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Historia eliminada.
        '404':
          description: Historia no encontrada.
        '500':
          description: Error interno del servidor.

  /pregunta_frecuente/get.php:
    get:
      tags:
        - "pregunta_frecuente"
=======
  /historia/post.php:
      post:
        tags:
          - "Historia"
        summary: Crea nueva información de contacto.
        security:
          - bearerAuth: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Historia'
        responses:
          '201':
            description: Información de contacto creada.

  /historia/delete.php:
      delete:
        tags:
          - "Historia"
        summary: Elimina una categoría de servicio.
        security:
          - bearerAuth: []
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        responses:
          '200':
            description: Información de contacto actualizada.



  /pregunta_frecuente/get.php:
    get:
>>>>>>> origin/Caro
      summary: Obtiene todas las preguntas frecuentes.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de preguntas frecuentes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PreguntaFrecuente'
<<<<<<< HEAD
        '404':
          description: No se encontraron preguntas frecuentes.
        '500':
          description: Error interno del servidor.

  /pregunta_frecuente/post.php:
    post:
      tags:
        - "pregunta_frecuente"
=======

  /pregunta_frecuente/post.php:
    post:
>>>>>>> origin/Caro
      summary: Crea una nueva pregunta frecuente.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreguntaFrecuente'
      responses:
        '201':
          description: Pregunta frecuente creada.
<<<<<<< HEAD
        '400':
          description: Solicitud incorrecta.
        '500':
          description: Error interno del servidor.

  /pregunta_frecuente/put.php:
    put:
      tags:
        - "pregunta_frecuente"
=======

  /pregunta_frecuente/put.php:
    put:
>>>>>>> origin/Caro
      summary: Actualiza una pregunta frecuente existente.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreguntaFrecuenteActualizada'
      responses:
        '200':
          description: Pregunta frecuente actualizada.
<<<<<<< HEAD
        '404':
          description: Pregunta frecuente no encontrada.
        '500':
          description: Error interno del servidor.

  /pregunta_frecuente/patch.php:
    patch:
      tags:
        - "pregunta_frecuente"
=======

  /pregunta_frecuente/patch.php:
    patch:
>>>>>>> origin/Caro
      summary: Actualiza parcialmente una pregunta frecuente.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreguntaFrecuenteParcial'
      responses:
        '200':
          description: Pregunta frecuente actualizada parcialmente.
<<<<<<< HEAD
        '404':
          description: Pregunta frecuente no encontrada.
        '500':
          description: Error interno del servidor.

  /pregunta_frecuente/delete.php:
    delete:
      tags:
        - "pregunta_frecuente"
=======

  /pregunta_frecuente/delete.php:
    delete:
>>>>>>> origin/Caro
      summary: Elimina una pregunta frecuente.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Pregunta frecuente eliminada.
<<<<<<< HEAD
        '404':
          description: Pregunta frecuente no encontrada.
        '500':
          description: Error interno del servidor.

  /parcela/get.php:
    get:
      tags:
        - "parcela"
=======

  /parcela/get.php:
    get:
>>>>>>> origin/Caro
      summary: Obtiene todas las parcelas.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de parcelas.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Parcela'
<<<<<<< HEAD
        '404':
          description: No se encontraron parcelas.
        '500':
          description: Error interno del servidor.

  /parcela/post.php:
    post:
      tags:
        - "parcela"
=======

  /parcela/post.php:
    post:
>>>>>>> origin/Caro
      summary: Crea una nueva parcela.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parcela'
      responses:
        '201':
          description: Parcela creada.
<<<<<<< HEAD
        '400':
          description: Solicitud incorrecta.
        '500':
          description: Error interno del servidor.

  /parcela/put.php:
    put:
      tags:
        - "parcela"
=======

  /parcela/put.php:
    put:
>>>>>>> origin/Caro
      summary: Actualiza una parcela existente.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParcelaActualizada'
      responses:
        '200':
          description: Parcela actualizada.
<<<<<<< HEAD
        '404':
          description: Parcela no encontrada.
        '500':
          description: Error interno del servidor.

  /parcela/patch.php:
    patch:
      tags:
        - "parcela"
=======

  /parcela/patch.php:
    patch:
>>>>>>> origin/Caro
      summary: Actualiza parcialmente una parcela.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParcelaParcial'
      responses:
        '200':
          description: Parcela actualizada parcialmente.
<<<<<<< HEAD
        '404':
          description: Parcela no encontrada.
        '500':
          description: Error interno del servidor.

  /parcela/delete.php:
    delete:
      tags:
        - "parcela"
=======

  /parcela/delete.php:
    delete:
>>>>>>> origin/Caro
      summary: Elimina una parcela.
      security:
        - bearerAuth: []
      requestBody:
<<<<<<< HEAD
        required: true
=======
>>>>>>> origin/Caro
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Parcela eliminada.
<<<<<<< HEAD
        '404':
          description: Parcela no encontrada.
        '500':
          description: Error interno del servidor.
=======
>>>>>>> origin/Caro

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CategoriaServicio:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre del servicio.
        descripcion:
          type: string
          description: Descripción del servicio.

    CategoriaServicioActualizada:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        descripcion:
          type: string

    CategoriaServicioParcial:
      type: object
      properties:
        id:
          type: integer
        descripcion:
          type: string

    InfoContacto:
      type: object
      properties:
        nombre:
          type: string
        telefono:
          type: string
        correo:
          type: string

    InfoContactoActualizada:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        telefono:
          type: string
        correo:
          type: string

    Historia:
      type: object
      properties:
        id:
          type: integer
        titulo:
          type: string
        contenido:
          type: string
        imagen:
          type: string

    PreguntaFrecuente:
      type: object
      properties:
        pregunta:
          type: string
        respuesta:
          type: string

    PreguntaFrecuenteActualizada:
      type: object
      properties:
        id:
          type: integer
        pregunta:
          type: string
        respuesta:
          type: string

    PreguntaFrecuenteParcial:
      type: object
      properties:
        id:
          type: integer
        respuesta:
          type: string

    Parcela:
      type: object
      properties:
        tipo:
          type: string
        lote:
          type: string
        servicio_id:
          type: integer

    ParcelaActualizada:
      type: object
      properties:
        id:
          type: integer
        tipo:
          type: string
        lote:
          type: string
        servicio_id:
          type: integer

    ParcelaParcial:
      type: object
      properties:
        id:
          type: integer
        tipo:
          type: string
        lote:
          type: string
