name: SLSA Generator Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Asegúrate de que se realiza un checkout completo

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Privacy Check
      uses: ./.github/actions/privacy-check
      with:
        repository: ${{ github.repository }}

<<<<<<< HEAD
    - name: Generate Builder
      uses: ./.github/actions/generate-builder
      with:
        repository: ${{ github.repository }}

    - name: Secure Checkout
      uses: /.github/actions/secure-builder-checkout@main
=======
    - name: SLSA Generator
      uses: slsa-framework/slsa-github-generator/.github/actions/generate-builder@v1.4.0
      with:
        allow-private-repository: true

    - name: Secure Checkout
      uses: slsa-framework/slsa-github-generator/.github/actions/secure-builder-checkout@main
>>>>>>> ac8e2f0 (Añadir acción de privacidad y configuración en el workflow)

    - name: Run tests
      run: composer run-script test
